:Author: Jake Uyechi
:Email: {jt.uyechi@outlook.com}
:Date: 19/04/2023
:Revision: 1.0
:License: Public Domain

= Project: {Acrylic Lights}

An edge-lit acrylic sign project including custom, programmable bases.

== Step 1: Installation

1. Open this project in the Arduino IDE
2. Add/Modify colors in the colors.h header file (or leave as-is)
3. Upload to an Arduino Nano - this should be compatible with the PCB files in this repository.

== Step 2: Assemble the circuit

Add electrical components to PCB and solder; there should be:

- 1 x Barrel Jack DC Through Hole Adapter
- 4 x JST-XH 2.54mm Male Headers
- 4 x Standard 4-Pin Breadboard Pushbuttons
- 1 x Arduino Nano
- 1 x Low Resistance Resistor (~220 Ohms)
- 4 x SMD Resistor (220 Ohms)
- 4 x SMD Resistor (10k Ohms)

== Step 3: Load the code

Upload the code contained in this sketch on to your board

=== Folder structure

....
 Acrylic Lights                => Arduino sketch folder
  ├── AcrylicLights.ino       => main Arduino file
  ├── colors.h            => Header file with color palettes
  └── ReadMe.adoc         => this file
....
